### PR TITLE
updated: output xml with comment node.

### PR DESCRIPTION
**Pull request by zhao5908**
The comment node should output as a block of comment text

### CODE REVIEW

**Comment by zhengchun** [comment]
Thanks for your commit, test is passed. But i have a question, when or under what case should we output comment node? At most of the time, comment node doesn't make sense in the XML document, we don't care about it.

**Comment by zhengchun** [comment]
belowing document output is incorrect.
```go
<?xml version="1.0" encoding="UTF-8"?>
	<!-- comment here-->
    <AAA> 
        <BBB> 
            <DDD> 
                <CCC> 
					<DDD/> 
					<!-- DDD -->
					<!-- DDD -->
					<!-- DDD -->
					<EEE/> 
				</CCC> 
				<!-- CCC -->
				<!-- CCC -->
            </DDD> 
		</BBB> 
		<!-- CCC -->
		<!-- CCC -->
        <CCC> 
			<DDD> 
			<!-- EEE -->
			<!-- EEE -->
			<!-- EEE -->
			<!-- EEE -->
                <EEE> 
					<DDD> 
					<!-- FFF -->
                        <FFF/> 
					</DDD> 
					<!-- FFF -->
					<!-- FFF -->
					<!-- FFF -->
                </EEE> 
            </DDD> 
        </CCC> 		
     </AAA>
```

should add following code to determine its level.
```go
for i := prev.level - level; i > 1; i-- {
	prev = prev.Parent
}
addSibling(prev.Parent, node)
```

**Comment by zhao5908** [comment]
Thanks for your advice, In my api proxy case, I parse xml-rpc, record some raw xml node value, then convert to other type. The OutputXML() should distinguish between text and comment. comment should been ignored, not as text.

**Comment by zhengchun** [comment]
Thanks, merged.

**Pull request merged**
